### PR TITLE
Si_dEdx update

### PR DESCRIPTION
**Pull request by StrahinjaLukic**
BEGINRELEASENOTES
- `SiTracker_dEdxProcessor` was adapted to determine the barrel/endcap type of tracker detector by checking the layering extension, rather than the type flag as before. 
- A bug was corrected in `SiTracker_dEdxProcessor` that caused miscalculation of total sensor thickness for some of the available dEdx estimators.

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
Can you please fix the rest of the warnings in `SiTracker_dEdxProcessor`

```
[101/103] Building CXX object CMakeFil...SiPID/src/SiTracker_dEdxProcessor.cc.o

In file included from .././Analysis/SiPID/include/SiTracker_dEdxProcessor.h:15:0,

                 from ../Analysis/SiPID/src/SiTracker_dEdxProcessor.cc:1:

.././Analysis/SiPID/include/LayerFinder.h: In member function 'double LayerResolver::SensitiveThicknessCheat(int) const':

.././Analysis/SiPID/include/LayerFinder.h:64:38: warning: unused parameter 'nLayer' [-Wunused-parameter]

   double SensitiveThicknessCheat(int nLayer) const { return sensThickCheatVal; };

                                      ^~~~~~

In file included from ../Analysis/SiPID/src/SiTracker_dEdxProcessor.cc:1:0:

.././Analysis/SiPID/include/SiTracker_dEdxProcessor.h: At global scope:

.././Analysis/SiPID/include/SiTracker_dEdxProcessor.h:48:7: warning: 'class SiTracker_dEdxProcessor' has pointer data members [-Weffc++]

 class SiTracker_dEdxProcessor : public Processor {

       ^~~~~~~~~~~~~~~~~~~~~~~

.././Analysis/SiPID/include/SiTracker_dEdxProcessor.h:48:7: warning:   but does not override 'SiTracker_dEdxProcessor(const SiTracker_dEdxProcessor&)' [-Weffc++]

.././Analysis/SiPID/include/SiTracker_dEdxProcessor.h:48:7: warning:   or 'operator=(const SiTracker_dEdxProcessor&)' [-Weffc++]

../Analysis/SiPID/src/SiTracker_dEdxProcessor.cc: In constructor 'SiTracker_dEdxProcessor::SiTracker_dEdxProcessor()':

../Analysis/SiPID/src/SiTracker_dEdxProcessor.cc:77:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

   for (int ibit=0; ibit<sizeof(int)*CHAR_BIT; ibit++) {
```

**Comment by StrahinjaLukic** [comment]
Ok. I did plan on solving the warnings...
Now I added the copy constructor and copy assignment to `SiTracker_dEdxProcessor`.

The warning about the unused variable is a bit non-trivial. This is a cheater function that needs to have the same signature as the functions that actually read the layer thickness so that the same function pointer can be used on both... Eventually I am not sure that the cheater function will be worth keeping at all. It was introduced as a workaround for missing features in the geometry.

**Comment by petricm** [comment]
for the cheater function you can do
```cpp
double SensitiveThicknessCheat(int /*nLayer*/) const { return sensThickCheatVal; };
```

**Comment by StrahinjaLukic** [comment]
Gasp... That compiled! 
Thanks.

**Pull request merged**
