### PR TITLE
BruteForceEcalGapFiller : Add missing information on calo hit type

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- BruteForceEcalGapFiller : Add missing information on calo hit type

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
I changed my editor (atom) to insert whitespace instead of tabs now. It seems that my last takes only into account the first additional whitespace case...

**Comment by andresailer** [comment]
Is this finished and ready to be merged/

**Comment by rete** [comment]
Yes. I squashed the four commits to make it clean

**Comment by andresailer** [comment]
Thanks for cleaning it up!

**Pull request merged**
