### PR TITLE
modified for SDHcal digitization

### PR DESCRIPTION
**Pull request by TiborILD**
modification for SDHcal digitization in Videau geometry

### CODE REVIEW

**Comment by andresailer** [comment]
MarlinReco is not yet migrated from SVN, you need to commit in SVN for now.
@gaede , please confirm

**Comment by gaede** [comment]
Confirmed. @TiborILD: can you please commit to SVN for the time being ?
Please refer to https://github.com/iLCSoft/ilcsoftDoc for the list of packages that are already migrated to Github (all other packages are still just mirrored from svn).

**Comment by petricm** [comment]
It is not migrated. A list can be seen here http://ilcsoft.github.io/ all the packages with unknown build status are on SVN.

**Comment by TiborILD** [comment]
Hello, 
I'am trying to checkout MarlinReco with my certificate (after some gymnastics with it..) 
svn co https://svnsrv.desy.de/svn/marlinreco/MarlinReco/trunk MarlinReco 
Passphrase for '/home/infor/kurca/.globus/newcert.p12': 
Authentication realm: <https://svnsrv.desy.de:443> Authorization Realm 
Password for 'kurca': 

But seems that I am not authorized to do it ? 

thanks 
Tibor 


De: "Andre Sailer" <notifications@github.com> 
À: "iLCSoft/MarlinReco" <MarlinReco@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 2 Mars 2017 18:15:53 
Objet: Re: [iLCSoft/MarlinReco] modified for SDHcal digitization (#1) 



Closed [ https://github.com/iLCSoft/MarlinReco/pull/1 | #1 ] .

**Comment by TiborILD** [comment]
Hello again, 
I am going to ask Gerald to commit a new stuff. He should have all the rights for MarlinReco. 


cheers 
Tibor 



De: "Tibor KURCA" <kurca@ipnl.in2p3.fr> 
À: "iLCSoft/MarlinReco" <reply@reply.github.com> 
Cc: "iLCSoft/MarlinReco" <MarlinReco@noreply.github.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 3 Mars 2017 11:56:05 
Objet: Re: [iLCSoft/MarlinReco] modified for SDHcal digitization (#1) 

Hello, 
I'am trying to checkout MarlinReco with my certificate (after some gymnastics with it..) 
svn co https://svnsrv.desy.de/svn/marlinreco/MarlinReco/trunk MarlinReco 
Passphrase for '/home/infor/kurca/.globus/newcert.p12': 
Authentication realm: <https://svnsrv.desy.de:443> Authorization Realm 
Password for 'kurca': 

But seems that I am not authorized to do it ? 

thanks 
Tibor 


De: "Andre Sailer" <notifications@github.com> 
À: "iLCSoft/MarlinReco" <MarlinReco@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 2 Mars 2017 18:15:53 
Objet: Re: [iLCSoft/MarlinReco] modified for SDHcal digitization (#1) 



Closed [ https://github.com/iLCSoft/MarlinReco/pull/1 | #1 ] .

**Comment by gaede** [comment]
Hi Tibor,

I added you to the developers for MarlinReco - please try again.

 Cheers, Frank.

------------------------------------ 
Dr. Frank Gaede
DESY - FLC
Phone:  +49 40 8998 4382    
Fax:    +49 40 8994 4382
E-mail: frank.gaede@desy.de

**Comment by TiborILD** [comment]
Hi Frank, 
It doesn't work for me ... it still wants a password from me (which one, I tried 
old one for lcgeo, but that doesn't work ...) 


But , I have asked Gerald to commit those changes and it's done now. 
As in the near future (?) all stuff should be migrated to github, 
I don't think that it has big sense to investigate what's wrong. 

thanks & cheers 
Tibor 


De: "Frank Gaede" <notifications@github.com> 
À: "iLCSoft/MarlinReco" <MarlinReco@noreply.github.com> 
Cc: "TiborILD" <kurca@in2p3.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 3 Mars 2017 12:39:07 
Objet: Re: [iLCSoft/MarlinReco] modified for SDHcal digitization (#1) 

Hi Tibor, 

I added you to the developers for MarlinReco - please try again. 

Cheers, Frank. 

------------------------------------ 
Dr. Frank Gaede 
DESY - FLC 
Phone: +49 40 8998 4382 
Fax: +49 40 8994 4382 
E-mail: frank.gaede@desy.de

**Pull request closed without merging**
