### PR TITLE
Add option to include full CovMat of neutrals

### PR DESCRIPTION
**Pull request by yradkhorrami**
BEGINRELEASENOTES
- An option is added to include full CovMat of neutral PFOs in jet error
ENDRELEASENOTES

### CODE REVIEW

**Comment by yradkhorrami** [comment]
Hi @rete , I found out I had not signed up in Travis CI. I followed the instruction and everything should be fine now.

**Comment by rete** [comment]
@yradkhorrami  Still doesn't work. Please send an email to TravisCI support explaining the problem.

**Comment by yradkhorrami** [comment]
> @yradkhorrami Still doesn't work. Please send an email to TravisCI support explaining the problem.

Thanks @rete , I'm sending the email to explain the issue.

**Comment by rete** [comment]
@yradkhorrami Looks like it is working now ! Thanks !

**Comment by yradkhorrami** [comment]
> @yradkhorrami Looks like it is working now ! Thanks !
@rete Very good to hear that. so I should synced my account.

**Review by rete — APPROVED** [review]

**Pull request merged**
