### PR TITLE
New SDHCAL digitizer version

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- New SDHCAL digitizer version from Lyon group (ggarillot)
  - step linking
  - two processors, one for applying the threshold, one for the threshold energy factors

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Do not merged before SDHCAL team approval

**Comment by gaede** [comment]
We need to make the release tags now ...

**Comment by ggarillot** [comment]
You can add 'Angular Correction' in the release notes.

**Comment by rete** [comment]
Done

**Pull request merged**
